//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polimer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctelag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctelag()
        {
            this.PostavHaYchet = new HashSet<PostavHaYchet>();
            this.Cpisanie = new HashSet<Cpisanie>();
        }
    
        public int IdCtelag { get; set; }
        public int IdCklad { get; set; }
        public int IdMaterial { get; set; }
        public string НомерСтелажа { get; set; }
        public string НомерПолки { get; set; }
        public decimal Осталось { get; set; }
    
        public virtual Cklad Cklad { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostavHaYchet> PostavHaYchet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cpisanie> Cpisanie { get; set; }
    }
}
