//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polimer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities : DbContext
    {
        public DiplomEntities()
            : base("name=DiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cklad> Cklad { get; set; }
        public virtual DbSet<Ctelag> Ctelag { get; set; }
        public virtual DbSet<EdIzmer> EdIzmer { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Poctavzik> Poctavzik { get; set; }
        public virtual DbSet<PostavHaYchet> PostavHaYchet { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
        public virtual DbSet<Cpisanie> Cpisanie { get; set; }
        public virtual DbSet<Polychat> Polychat { get; set; }
    }
}
