//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polimer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostavHaYchet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostavHaYchet()
        {
            this.Poctavzik = new HashSet<Poctavzik>();
        }
    
        public int IdPostHaYchet { get; set; }
        public System.DateTime Дата { get; set; }
        public int НомерДокумента { get; set; }
        public int IdPoctav { get; set; }
        public int IdMaterial { get; set; }
        public decimal Цена { get; set; }
        public decimal Количество { get; set; }
        public int IdCtelag { get; set; }
    
        public virtual Ctelag Ctelag { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poctavzik> Poctavzik { get; set; }
    }
}
